### ISSUE TITLE
Keyword-argument failure

### ISSUE THREAD

**Issue by cstjean** [one-more-minute/MacroTools.jl#4]
Thank you for MacroTools, it's super useful! I think I found a bug

```julia
let ex = :(function foo(a, b, c; kw=1) a+b+c end)
    @capture(ex, function foo(arg1_, args__) body__ end)
    arg1
end
> :($(Expr(:parameters, :(x=1))))
```

It works fine without `kw=1`

**Comment by cstjean** [comment]
Hmm, it works if the pattern is `function foo(arg1_, args__; kwargs__)`, so maybe the issue is just that `@capture` should return `false` in the above example, but doesn't?

**Comment by one-more-minute** [comment]
Glad you like it!

So the problem here is that the keyword arguments are becoming a kind of implicit first argument in the AST:
```julia
:(f(a,b,c; kw=1)) == :(f($(Expr(:parameters, :(kw=1)), a, b, c))
```
so when you try to match on the first argument, you get the `:parameters` expression. Unfortunately, it's the Julia AST format that's weird here – MacroTools' behaviour is completely consistent with how it operates elsewhere, which means it's tricky to fix with out making a weird special case out of it.

I'm open to suggestions, but the best thing might just be to be aware of it, and to match on keyword args explicitly where needed.

**Comment by cstjean** [comment]
That makes sense. I'll code around it, I wouldn't want to add an ugly special-case!
